### ISSUE TITLE
How to set different path to different languages

### ISSUE THREAD

**Issue by SlippyJimmy** [quantonganh/snippets-ls#2]
<img width="783" alt="image" src="https://github.com/quantonganh/snippets-ls/assets/45062658/6b662378-acca-4b50-8c48-4faee4c6453f">

**Comment by quantonganh** [comment]
You can do it by using a different name for each language server:

```toml
[[language]]
name = "go"
formatter = { command = "goimports"}
language-servers = ["gopls", "snippets-ls-go"]

[language-server.snippets-ls-go]
command = "snippets-ls"
args = ["-config", "/Users/quantong/.config/helix/go-snippets.json"]

[[language]]
name = "rust"
language-servers = ["rust-analyzer", "snippets-ls-rust"]

[language-server.snippets-ls-rust]
command = "snippets-ls"
args = ["-config", "/Users/quantong/.config/helix/rust-snippets.json"]
```
